# Generated by Django 2.2.1 on 2019-05-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pushnotificationapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='p256dh',
            new_name='keys',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='auth',
        ),
    ]
